---
title: "LVEDA.Rmd"
output: html_document
date: "2023-07-28"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(scipen = 0, digits = 3)  # controls base R output
# check if you have ISLR package, if not, install it
if(!require('pacman')) {install.packages('pacman')}
pacman::p_load(ISLR, readxl, tidyverse, magrittr, dplyr, ggplot2, ggrepel, data.table, lubridate, ggpubr, patchwork)
```


```{r}
# coordinates are 36.17, -115.14

chicago_full <- fread("data/Chicago_Solar_Irradiation/chicago.csv")

head(chicago_full)
str(chicago_full)

chicago_full$Date <- make_datetime(year=chicago_full$Year, month=chicago_full$Month, day=chicago_full$Day, hour=chicago_full$Hour, min=chicago_full$Minute)
chicago_full %>% ggplot(aes(x=Date, y=Temperature)) + geom_line(color="blue") 

plots <- NULL

# create a graph for each of the 20 years
temp <- chicago_full %>% 
  # average by year-month
  group_by(Year, Month) %>% 
  summarise(Temperature = mean(Temperature, na.rm = TRUE), .groups = "drop") %>% 
  ggplot() +
  geom_line(aes(x = Month, y = Temperature, color = factor(Year))) +
  scale_x_continuous(breaks = 1:12, labels = month.abb, minor_breaks = NULL) +
  labs(title = "Average Temperature by Month", colour = "Year")

dew <- chicago_full %>% 
  # average by year-month
  group_by(Year, Month) %>% 
  summarise(`Dew Point` = mean(`Dew Point`, na.rm = TRUE), .groups = "drop") %>% 
  ggplot() +
  geom_line(aes(x = Month, y = `Dew Point`, color = factor(Year))) +
  scale_x_continuous(breaks = 1:12, labels = month.abb, minor_breaks = NULL) +
  labs(title = "Average Dew Point by Month", colour = "Year")

humidity <- chicago_full %>% 
  # average by year-month
  group_by(Year, Month) %>% 
  summarise(`Relative Humidity` = mean(`Relative Humidity`, na.rm = TRUE), .groups = "drop") %>% 
  ggplot() +
  geom_line(aes(x = Month, y = `Relative Humidity`, color = factor(Year))) +
  scale_x_continuous(breaks = 1:12, labels = month.abb, minor_breaks = NULL) +
  labs(title = "Average Relative Humidity by Month", colour = "Year")

albedo <- chicago_full %>% 
  # average by year-month
  group_by(Year, Month) %>% 
  summarise(`Surface Albedo` = mean(`Surface Albedo`, na.rm = TRUE), .groups = "drop") %>% 
  ggplot() +
  geom_line(aes(x = Month, y = `Surface Albedo`, color = factor(Year))) +
  scale_x_continuous(breaks = 1:12, labels = month.abb, minor_breaks = NULL) +
  labs(title = "Average Surface Albedo by Month", colour = "Year")

wind <- chicago_full %>% 
  # average by year-month
  group_by(Year, Month) %>% 
  summarise(`Wind Speed` = mean(`Wind Speed`, na.rm = TRUE), .groups = "drop") %>% 
  ggplot() +
  geom_line(aes(x = Month, y = `Wind Speed`, color = factor(Year))) +
  scale_x_continuous(breaks = 1:12, labels = month.abb, minor_breaks = NULL) +
  labs(title = "Average Wind Speed by Month", colour = "Year")

pressure <- chicago_full %>% 
  # average by year-month
  group_by(Year, Month) %>% 
  summarise(`Pressure` = mean(`Pressure`, na.rm = TRUE), .groups = "drop") %>% 
  ggplot() +
  geom_line(aes(x = Month, y = `Pressure`, color = factor(Year))) +
  scale_x_continuous(breaks = 1:12, labels = month.abb, minor_breaks = NULL) +
  labs(title = "Average Pressure by Month", colour = "Year")

windD <- chicago_full %>% 
  # average by year-month
  group_by(Year, Month) %>% 
  summarise(`Wind Direction` = mean(`Wind Direction`, na.rm = TRUE), .groups = "drop") %>% 
  ggplot() +
  geom_line(aes(x = Month, y = `Wind Direction`, color = factor(Year))) +
  scale_x_continuous(breaks = 1:12, labels = month.abb, minor_breaks = NULL) +
  labs(title = "Average Wind Direction by Month", colour = "Year")

precip <- chicago_full %>% 
  # average by year-month
  group_by(Year, Month) %>% 
  summarise(`Precipitable Water` = mean(`Precipitable Water`, na.rm = TRUE), .groups = "drop") %>% 
  ggplot() +
  geom_line(aes(x = Month, y = `Precipitable Water`, color = factor(Year))) +
  scale_x_continuous(breaks = 1:12, labels = month.abb, minor_breaks = NULL) +
  labs(title = "Average Precipitable Water by Month", colour = "Year")

zenith <- chicago_full %>% ggplot(aes(x=`Solar Zenith Angle`)) + geom_histogram(bins=360) + scale_x_continuous(breaks=seq(0,360,30)) + labs(title="Solar Zenith Angle Histogram")

ghi <- chicago_full %>% 
  # average by year-month
  group_by(Year, Month) %>% 
  summarise(`GHI` = mean(`GHI`, na.rm = TRUE), .groups = "drop") %>% 
  ggplot() +
  geom_line(aes(x = Month, y = `GHI`, color = factor(Year))) +
  scale_x_continuous(breaks = 1:12, labels = month.abb, minor_breaks = NULL) +
  labs(title = "Average GHI by Month", colour = "Year")

cloud <- chicago_full %>% ggplot(aes(x=`Cloud Type`)) + geom_histogram(bins=11) + scale_x_continuous(breaks=seq(0,10,1))+ labs(title="Cloud Type")

vsTemp <- chicago_full %>% 
  group_by(Year, Month) %>% 
  summarise(`GHI` = mean(`GHI`, na.rm=TRUE), `Temperature` = mean(`Temperature`, na.rm=TRUE)) %>% 
  ggplot(aes(x=`Temperature`, y=GHI)) + geom_point()

vsDew <- chicago_full %>% 
  group_by(Year, Month) %>% 
  summarise(`GHI` = mean(`GHI`, na.rm=TRUE), `Dew Point` = mean(`Dew Point`, na.rm=TRUE)) %>% 
  ggplot(aes(x=`Dew Point`, y=GHI)) + geom_point()

vsHumid <- chicago_full %>% 
  group_by(Year, Month) %>% 
  summarise(`GHI` = mean(`GHI`, na.rm=TRUE), `Relative Humidity` = mean(`Relative Humidity`, na.rm=TRUE)) %>% 
  ggplot(aes(x=`Relative Humidity`, y=GHI)) + geom_point()

vsAlbedo <- chicago_full %>% 
  group_by(Year, Month) %>% 
  summarise(`GHI` = mean(`GHI`, na.rm=TRUE), `Surface Albedo` = mean(`Surface Albedo`, na.rm=TRUE)) %>% 
  ggplot(aes(x=`Surface Albedo`, y=GHI)) + geom_point()

vsWindS <- chicago_full %>% 
  group_by(Year, Month) %>% 
  summarise(`GHI` = mean(`GHI`, na.rm=TRUE), `Wind Speed` = mean(`Wind Speed`, na.rm=TRUE)) %>% 
  ggplot(aes(x=`Wind Speed`, y=GHI)) + geom_point()

vsPressure <- chicago_full %>% 
  group_by(Year, Month) %>% 
  summarise(`GHI` = mean(`GHI`, na.rm=TRUE), `Pressure` = mean(`Pressure`, na.rm=TRUE)) %>% 
  ggplot(aes(x=`Pressure`, y=GHI)) + geom_point()

vsWindD <- chicago_full %>% 
  group_by(Year, Month) %>% 
  summarise(`GHI` = mean(`GHI`, na.rm=TRUE), `Wind Direction` = mean(`Wind Direction`, na.rm=TRUE)) %>% 
  ggplot(aes(x=`Wind Direction`, y=GHI)) + geom_point()

vsPrecip <- chicago_full %>% 
  group_by(Year, Month) %>% 
  summarise(`GHI` = mean(`GHI`, na.rm=TRUE), `Precipitable Water` = mean(`Precipitable Water`, na.rm=TRUE)) %>% 
  ggplot(aes(x=`Precipitable Water`, y=GHI)) + geom_point()

vsWindD <- chicago_full %>% 
  group_by(Year, Month) %>% 
  summarise(`GHI` = mean(`GHI`, na.rm=TRUE), `Wind Direction` = mean(`Wind Direction`, na.rm=TRUE)) %>% 
  ggplot(aes(x=`Wind Direction`, y=GHI)) + geom_point()

vsZenith <- chicago_full %>%
  group_by(`Solar Zenith Angle`) %>%
  summarise(average_ghi = mean(GHI, na.rm=TRUE)) %>%
  ggplot(aes(x=`Solar Zenith Angle`, y=average_ghi)) + geom_point()

vsCloud <- chicago_full %>%
  group_by(`Cloud Type`) %>%
  summarise(average_ghi = mean(GHI, na.rm=TRUE)) %>%
  ggplot(aes(x=`Cloud Type`, y=average_ghi)) + geom_point()

plots <- list(temp, dew, humidity, albedo, wind, pressure, windD, precip, zenith, ghi, cloud)
plots
plotsVs <- list(vsTemp, vsDew, vsHumid, vsAlbedo, vsWindS, vsPressure, vsWindD, vsPrecip, vsZenith, vsCloud)
plotsVs

summary(chicago_full)
```

```{r}
#names(chicago_full)
chicago_full$Zenith_Bins <- cut(chicago_full$`Solar Zenith Angle`, breaks = seq(0, 180, by = 10))

# Plotting irradiance vs zenith angle
# The gray dots are outliers of solar irradiance, likely caused by clouds
ggplot(data = chicago_full, aes(x = Zenith_Bins, y = GHI)) +
  geom_boxplot(outlier.color = "gray", size = 0.5) +
  labs(x = "Solar Zenith Angle (degrees)", y = "Global Horizontal Irradiance (W/m²)",
       title = "Distribution of GHI for Different Solar Zenith Angle (Grouped by bins of 10 degrees)") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

# plotting solar zenith against time of day
ggplot(data = chicago_full, aes(x = Hour, y = `Solar Zenith Angle`, group = interaction(Month, Day), color = factor(Month))) +
  geom_line() +
  labs(x = "Time of Day (Hour)", y = "Solar Zenith Angle (degrees)",
       title = "Solar Zenith Angle by Time of Day (Spaghetti Plot)") +
  scale_color_discrete(name = "Month", labels = c("January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December")) +
  theme_minimal() +
  theme(legend.position = "top", axis.text.x = element_text(angle = 45, hjust = 1))


# shows the difference between solstices, and their effect on solar zenith angle
filtered_data <- chicago_full %>%
  filter(Month %in% c(6, 12))
ggplot(data = filtered_data, aes(x = Hour, y = `Solar Zenith Angle`, group = interaction(Month, Day), color = factor(Month))) +
  geom_line() +
  labs(x = "Time of Day (Hour)", y = "Solar Zenith Angle (degrees)",
       title = "Solar Zenith Angle by Time of Day (June and December Only)") +
  scale_color_discrete(name = "Month", labels = c("June", "December")) +
  theme_minimal() +
  theme(legend.position = "top", axis.text.x = element_text(angle = 45, hjust = 1))


#plotting how solar irradiance is affected by time of month
chicago_full$Month <- factor(chicago_full$Month, levels = 1:12, labels = c("Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"))
agg_data <- chicago_full %>%
  group_by(Month, Hour) %>%
  summarize(Avg_GHI = mean(GHI))
ggplot(data = chicago_full, aes(x = Hour, y = GHI, group = interaction(Month, Hour), color = Month)) +
  geom_line(size = 1.5, alpha = 0.7) +  # Set the size to 1.5 (adjust as needed)
  labs(x = "Hour of the Day", y = "Average Global Horizontal Irradiance (W/m²)",
       title = "Average Solar Irradiance by Hour for Each Month (Spaghetti Plot)") +
  scale_x_continuous(breaks = seq(0, 23, by = 1)) +
  theme_minimal() +
  theme(legend.position = "top", axis.text.x = element_text(angle = 45, hjust = 1))


# num_unique_clouds <- chicago_full %>%
#   distinct(Cloud_Type) %>%
#   nrow()
chicago_full <- chicago_full %>%
  rename(Cloud_Type = `Cloud Type`)
chicago_full$Cloud_Type <- factor (chicago_full$Cloud_Type)
# Effect of clouds on GHI
ggplot(data = chicago_full, aes(x = Cloud_Type, y = GHI)) +
  stat_summary(data = subset(chicago_full, `Solar Zenith Angle` >= 0 & `Solar Zenith Angle` <= 80),
               fun = "mean", geom = "bar", fill = "skyblue", color = "black") +
  labs(x = "Cloud_Type", y = "Mean Global Horizontal Irradiance (W/m²)",
       title = "Effect of Cloud Type on Irradiance (Solar Zenith: 0-80 degrees)") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

```

```{r}
names(chicago_full)

# temperature vs irradiance boxplot
ggplot(data = subset(chicago_full, `Solar Zenith Angle` >= 0 & `Solar Zenith Angle` <= 80),
       aes(x = cut(Temperature, breaks = seq(min(Temperature), max(Temperature) + 2, by = 2)), y = GHI)) +
  geom_boxplot() +
  labs(x = "Temperature (°C)", y = "Global Horizontal Irradiance (W/m²)",
       title = "Temperature vs. Global Horizontal Irradiance (Solar Zenith: 0-80 degrees)") +
  theme_minimal()


#Surface Albedo vs Irradiance for sunlight hours
filtered_data <- chicago_full %>%
  filter(`Solar Zenith Angle` >= 0 & `Solar Zenith Angle` <= 80,
         `Surface Albedo` >= 0.05 & `Surface Albedo` <= 0.30)
filtered_data <- filtered_data %>%
  mutate(Albedo_Bin = cut(`Surface Albedo`, breaks = seq(0.05, 0.300, by = 0.002)),)
ggplot(data = filtered_data, aes(x = Albedo_Bin, y = GHI)) +
  geom_boxplot(outlier.color = "gray", size = 0.5) +
  labs(x = "Surface Albedo", y = "Global Horizontal Irradiance (W/m²)",
       title = "Distribution of GHI for Different Surface Albedo (Grouped by bins of 0.002)\n(Zenith: 0-80 degrees)") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

#Relative humidity vs Solar Irradiance for zentih 0-80
filtered_data <- filtered_data %>%
  mutate(RelHumidity_Bin = cut(`Relative Humidity`, breaks = seq(0, 100, by = 2.5)))
ggplot(data = filtered_data, aes(x = RelHumidity_Bin, y = GHI)) +
  geom_boxplot(fill = "skyblue", color = "black") +
  labs(x = "Relative Humidity (%)", y = "Global Horizontal Irradiance (W/m²)",
       title = "GHI vs. Relative Humidity (Zenith: 0-80 degrees, Bin Size: 2.5%)") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

#Precipitable Water vs GHI (for hours during sunlight)
filtered_data <- filtered_data %>%
  mutate(PrecipitableWater_Bin = cut(`Precipitable Water`, breaks = seq(min(`Precipitable Water`), max(`Precipitable Water`), by = 0.15)))
ggplot(data = filtered_data, aes(x = PrecipitableWater_Bin, y = GHI)) +
  geom_boxplot(fill = "skyblue", color = "black") +
  labs(x = "Precipitable Water (Bin Size: 0.05)", y = "Global Horizontal Irradiance (W/m²)",
       title = "GHI vs. Precipitable Water (Zenith: 0-80 degrees)") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

```




