---
title: "practice_rmd_file"
author:
- KD 
output:
  html_document:
    code_folding: show
    highlight: haddock
    number_sections: yes
    theme: lumen
    toc: yes
    toc_depth: 4
    toc_float: yes
  pdf_document:
    number_sections: yes
    toc: yes
    toc_depth: '4'
  word_document:
    toc: yes
    toc_depth: '4'
urlcolor: blue
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.width=8, fig.height=4)
options(scipen = 0, digits = 3)  # controls base R output
if(!require('pacman')) {
  install.packages('pacman')
}
pacman::p_load(ggplot2, dplyr, tidyverse, gridExtra, ggrepel, plotly, skimr, tidytext, data.table, xml2)
```

```{r}
consumption <- read.csv("data/hourly-consumption/AEP_hourly.csv", header=T, stringsAsFactors = FALSE)
xml_data <- read_xml("C:/Users/vdich/Documents/R_projects/final_project_repo/Electricity_Balance_Data_2011-2019_DK1.xml")
rows <- xml_find_all(xml_data, "//row")

# Initialize lists to store data for each column
HourUTC <- list()
HourDK <- list()
PriceArea <- list()
GrossCon <- list()
NetCon <- list()
LocalPowerProd <- list()
OffshoreWindPower <- list()
OnshoreWindPower <- list()
CentralProd <- list()
ElectricBoilerCon <- list()
SolarPowerProd <- list()
ExchangeContinent <- list()
ExchangeGreatBelt <- list()
ExchangeNordicCountries <- list()

# Set the maximum number of rows to process
max_rows <- 1000

# Loop through each row and extract data for each column
for (i in seq_len(min(max_rows, length(rows)))) {
  row <- rows[[i]]
  
  # Print progress message
  cat("Processing row", i, "of", min(max_rows, length(rows)), "\n")
  
  # Extract data for each column
  HourUTC <- c(HourUTC, xml_text(xml_find_first(row, "./HourUTC")))
  HourDK <- c(HourDK, xml_text(xml_find_first(row, "./HourDK")))
  PriceArea <- c(PriceArea, xml_text(xml_find_first(row, "./PriceArea")))
  GrossCon <- c(GrossCon, xml_text(xml_find_first(row, "./GrossCon")))
  NetCon <- c(NetCon, xml_text(xml_find_first(row, "./NetCon")))
  LocalPowerProd <- c(LocalPowerProd, xml_text(xml_find_first(row, "./LocalPowerProd")))
  OffshoreWindPower <- c(OffshoreWindPower, xml_text(xml_find_first(row, "./OffshoreWindPower")))
  OnshoreWindPower <- c(OnshoreWindPower, xml_text(xml_find_first(row, "./OnshoreWindPower")))
  CentralProd <- c(CentralProd, xml_text(xml_find_first(row, "./CentralProd")))
  ElectricBoilerCon <- c(ElectricBoilerCon, xml_text(xml_find_first(row, "./ElectricBoilerCon")))
  SolarPowerProd <- c(SolarPowerProd, xml_text(xml_find_first(row, "./SolarPowerProd")))
  ExchangeContinent <- c(ExchangeContinent, xml_text(xml_find_first(row, "./ExchangeContinent")))
  ExchangeGreatBelt <- c(ExchangeGreatBelt, xml_text(xml_find_first(row, "./ExchangeGreatBelt")))
  ExchangeNordicCountries <- c(ExchangeNordicCountries, xml_text(xml_find_first(row, "./ExchangeNordicCountries")))
}

# Create a data.frame from the extracted data
data_df <- data.frame(
  HourUTC, HourDK, PriceArea, GrossCon, NetCon, LocalPowerProd,
  OffshoreWindPower, OnshoreWindPower, CentralProd, ElectricBoilerCon,
  SolarPowerProd, ExchangeContinent, ExchangeGreatBelt, ExchangeNordicCountries
)

# Write the data.frame to a CSV file
write.csv(data_df, file = "C:/Users/vdich/Documents/R_projects/final_project_repo/output.csv", row.names = FALSE)




#names(consumption)
#consumption[1:3,]
#We convert the "Datetime" column to a proper datetime format using as.POSIXct(). This is necessary to extract the hour later on.
consumption$Datetime <- as.POSIXct(consumption$Datetime, format = "%Y-%m-%d %H:%M:%S")
#We extract the hour from the "Datetime" column using format() and store it in a new column called "Hour."
consumption$Hour <- format(consumption$Datetime, "%H")
#convert hour to numeric
consumption$Hour <- as.numeric(consumption$Hour)
# Calculate the hourly averages
hourly_averages <- consumption %>%
  group_by(Hour) %>%
  summarize(Average_Power_Consumption = mean(AEP_MW, na.rm = TRUE))

ggplot(hourly_averages, aes(x = factor(Hour), y = Average_Power_Consumption)) +
  geom_bar(stat = "identity", fill = "lightblue", color = "black") +
  labs(x = "Hour of Day", y = "Average Power Consumption", title = "Average Power Consumption by Hour")

consumption2005 <- subset(consumption, format(Datetime, "%Y") == "2007")
ggplot(consumption2005, aes(x = Hour, y = AEP_MW)) +
  geom_point(color = "blue", size = 2.5) +
  labs(x = "Hour of Day", y = "kWh Consumption", title = "Scatter Plot of kWh Consumption by Hour in 2007")
```



