---
title: "A Machine Learning Based Approach to Modeling Solar Power Output"
output: html_document
date: "2023-08-03"
---

```{r}
if(!require('pacman')) {install.packages('pacman')}
pacman::p_load(dplyr, ggplot2, ggrepel, data.table, lubridate, ggpubr, patchwork, car, glmnet, sf, purrr)
```

## Cleaning
```{r, preprocessing}

# This function removes the first two rows of a given dataframe
remove_first_two <- function(x) {
  x[-(1:2)]
}

# read in the raw files
lv_files <- list.files(path="data/Las_Vegas_Solar_Irradiation/raw", pattern="\\.csv$", full.names=TRUE)
lv_files_no_path <- list.files(path="data/Las_Vegas_Solar_Irradiation/raw", pattern="\\.csv$", full.names=FALSE)
lv_read <- lapply(lv_files, readLines)

# remove the info lines
lv_read <- lapply(lv_read, remove_first_two)

# rewrite to a new file
for(i in 1:length(lv_files)) {
  fwrite(lv_read[i], file=(paste0("data/Las_Vegas_Solar_Irradiation/cleaned/",lv_files_no_path[i])), quote=FALSE)
}

# join all Las Vegas data into one dataframe
lv_files_cleaned <- list.files(path="data/Las_Vegas_Solar_Irradiation/cleaned", pattern="\\.csv$", full.names=TRUE)
lv_cleaned <- lapply(lv_files_cleaned, fread)
lv_full <- lv_cleaned %>% reduce(full_join)
fwrite(lv_full, file="data/Las_Vegas_Solar_Irradiation/LV.csv")

# same process for New York and Chicago
ny_files <- list.files(path="data/NY_Solar_Irradiation/raw", pattern="\\.csv$", full.names=TRUE)
ny_files_no_path <- list.files(path="data/NY_Solar_Irradiation/raw", pattern="\\.csv$", full.names=FALSE)
ny_read <- lapply(ny_files, readLines)

ny_read <- lapply(ny_read, remove_first_two)

for(i in 1:length(ny_files)) {
  fwrite(ny_read[i], file=(paste0("data/NY_Solar_Irradiation/cleaned/",ny_files_no_path[i])), quote=FALSE)
}

ny_files_cleaned <- list.files(path="data/NY_Solar_Irradiation/cleaned", pattern="\\.csv$", full.names=TRUE)
ny_cleaned <- lapply(ny_files_cleaned, fread)

ny_full <- ny_cleaned %>% reduce(full_join)

fwrite(ny_full, file="data/NY_Solar_Irradiation/ny.csv")

chicago_files <- list.files(path="data/Chicago_Solar_Irradiation/raw", pattern="\\.csv$", full.names=TRUE)
chicago_files_no_path <- list.files(path="data/Chicago_Solar_Irradiation/raw", pattern="\\.csv$", full.names=FALSE)
chicago_read <- lapply(chicago_files, readLines)
chicago_read <- lapply(chicago_read, remove_first_two)

for(i in 1:length(chicago_files)) {
  fwrite(chicago_read[i], file=(paste0("data/Chicago_Solar_Irradiation/cleaned/",chicago_files_no_path[i])), quote=FALSE)
}


chicago_files_cleaned <- list.files(path="data/Chicago_Solar_Irradiation/cleaned", pattern="\\.csv$", full.names=TRUE)
chicago_cleaned <- lapply(chicago_files_cleaned, fread)

chicago_full <- chicago_cleaned %>% reduce(full_join)

fwrite(chicago_full, file="data/Chicago_Solar_Irradiation/chicago.csv")

chicago_full <- chicago_full$Location = 'Chicago'
ny_full <- ny_full$Location = 'New York'
lv_full <- lv_full$Location = 'Las Vegas'


# put all data together into one large dataframe
data = list(lv_full, ny_full, chicago_full)
all_data <- data %>% reduce(full_join)
fwrite(all_data, file="data/SolarFull.csv")
```

## EDA on Cleaned Data
```{r}

LV <- fread("data/Las_Vegas_Solar_Irradiation/LV.csv")
NY <- fread("data/NY_Solar_Irradiation/ny.csv")
Chi <- fread("data/Chicago_Solar_Irradiation/chicago.csv")

city_data <- list(LV, NY, Chi)
allPlots <- list(NULL, NULL, NULL)

for(i in (1:3)) {
  head(city_data[[i]])
  str(city_data[[i]])
  
  city_data[[i]]$Date <- make_datetime(year=city_data[[i]]$Year, month=city_data[[i]]$Month, day=city_data[[i]]$Day, hour=city_data[[i]]$Hour, min=city_data[[i]]$Minute)
  city_data[[i]] %>% ggplot(aes(x=Date, y=Temperature)) + geom_line(color="blue") 
  
  plots <- NULL
  
  # create a graph for each of the 20 years
  temp <- city_data[[i]] %>% 
    # average by year-month
    group_by(Year, Month) %>% 
    summarise(Temperature = mean(Temperature, na.rm = TRUE), .groups = "drop") %>% 
    ggplot() +
    geom_line(aes(x = Month, y = Temperature, color = factor(Year))) +
    scale_x_continuous(breaks = 1:12, labels = month.abb, minor_breaks = NULL) +
    labs(title = "Average Temperature by Month", x="Month", y="Temp (°C)", colour = "Year")
  
  dew <- city_data[[i]] %>% 
    # average by year-month
    group_by(Year, Month) %>% 
    summarise(`Dew Point` = mean(`Dew Point`, na.rm = TRUE), .groups = "drop") %>% 
    ggplot() +
    geom_line(aes(x = Month, y = `Dew Point`, color = factor(Year))) +
    scale_x_continuous(breaks = 1:12, labels = month.abb, minor_breaks = NULL) +
    labs(title = "Average Dew Point by Month", x="Month", y="Dew Point (°C)", colour = "Year")
  
  humidity <- city_data[[i]] %>% 
    # average by year-month
    group_by(Year, Month) %>% 
    summarise(`Relative Humidity` = mean(`Relative Humidity`, na.rm = TRUE), .groups = "drop") %>% 
    ggplot() +
    geom_line(aes(x = Month, y = `Relative Humidity`, color = factor(Year))) +
    scale_x_continuous(breaks = 1:12, labels = month.abb, minor_breaks = NULL) +
    labs(title = "Average Relative Humidity by Month", x = "Month", y = "Relative Humidity (%)", colour = "Year")
  
  albedo <- city_data[[i]] %>% 
    # average by year-month
    group_by(Year, Month) %>% 
    summarise(`Surface Albedo` = mean(`Surface Albedo`, na.rm = TRUE), .groups = "drop") %>% 
    ggplot() +
    geom_line(aes(x = Month, y = `Surface Albedo`, color = factor(Year))) +
    scale_x_continuous(breaks = 1:12, labels = month.abb, minor_breaks = NULL) +
    labs(title = "Average Surface Albedo by Month", x = "Month", y = "Surface Albedo (%)", colour = "Year")
  
  wind <- city_data[[i]] %>% 
    # average by year-month
    group_by(Year, Month) %>% 
    summarise(`Wind Speed` = mean(`Wind Speed`, na.rm = TRUE), .groups = "drop") %>% 
    ggplot() +
    geom_line(aes(x = Month, y = `Wind Speed`, color = factor(Year))) +
    scale_x_continuous(breaks = 1:12, labels = month.abb, minor_breaks = NULL) +
    labs(title = "Average Wind Speed by Month", y="Wind Speed (m/s)", colour = "Year")
  
  pressure <- city_data[[i]] %>% 
    # average by year-month
    group_by(Year, Month) %>% 
    summarise(`Pressure` = mean(`Pressure`, na.rm = TRUE), .groups = "drop") %>% 
    ggplot() +
    geom_line(aes(x = Month, y = `Pressure`, color = factor(Year))) +
    scale_x_continuous(breaks = 1:12, labels = month.abb, minor_breaks = NULL) +
    labs(title = "Average Pressure by Month", y="Pressure (mbar)", colour = "Year")
  
  windD <- city_data[[i]] %>% 
    # average by year-month
    group_by(Year, Month) %>% 
    summarise(`Wind Direction` = mean(`Wind Direction`, na.rm = TRUE), .groups = "drop") %>% 
    ggplot() +
    geom_line(aes(x = Month, y = `Wind Direction`, color = factor(Year))) +
    scale_x_continuous(breaks = 1:12, labels = month.abb, minor_breaks = NULL) +
    labs(title = "Average Wind Direction by Month", y="Wind Direction (°)", colour = "Year")
  
  precip <- city_data[[i]] %>% 
    # average by year-month
    group_by(Year, Month) %>% 
    summarise(`Precipitable Water` = mean(`Precipitable Water`, na.rm = TRUE), .groups = "drop") %>% 
    ggplot() +
    geom_line(aes(x = Month, y = `Precipitable Water`, color = factor(Year))) +
    scale_x_continuous(breaks = 1:12, labels = month.abb, minor_breaks = NULL) +
    labs(title = "Average Precipitable Water by Month", y = "Precipitable Water (cm)", colour = "Year")
  
  zenith <- city_data[[i]] %>% ggplot(aes(x=`Solar Zenith Angle`)) + geom_histogram(bins=360) + scale_x_continuous(breaks=seq(0,360,30)) + labs(title="Solar Zenith Angle Histogram", x = "Degrees", y = "Count")
  
  ghi <- city_data[[i]] %>% 
    # average by year-month
    group_by(Year, Month) %>% 
    summarise(`GHI` = mean(`GHI`, na.rm = TRUE), .groups = "drop") %>% 
    ggplot() +
    geom_line(aes(x = Month, y = `GHI`, color = factor(Year))) +
    scale_x_continuous(breaks = 1:12, labels = month.abb, minor_breaks = NULL) +
    labs(title = "Average GHI by Month", colour = "Year", y = "Avg GHI (w/m^2)")
  
  cloud <- city_data[[i]] %>% ggplot(aes(x=`Cloud Type`)) + geom_histogram(bins=11) + scale_x_continuous(breaks=seq(0,10,1))+ labs(title="Cloud Type")
  
  vsTemp <- city_data[[i]] %>% 
    group_by(Year, Month) %>% 
    summarise(`GHI` = mean(`GHI`, na.rm=TRUE), `Temperature` = mean(`Temperature`, na.rm=TRUE)) %>% 
    ggplot(aes(x=`Temperature`, y=GHI)) + geom_point() + labs(title="Average GHI by Month vs. Temperature")
  
  vsDew <- city_data[[i]] %>% 
    group_by(Year, Month) %>% 
    summarise(`GHI` = mean(`GHI`, na.rm=TRUE), `Dew Point` = mean(`Dew Point`, na.rm=TRUE)) %>% 
    ggplot(aes(x=`Dew Point`, y=GHI)) + geom_point() + labs(title="Average GHI by Month vs. Dew Point")
  
  vsHumid <- city_data[[i]] %>% 
    group_by(Year, Month) %>% 
    summarise(`GHI` = mean(`GHI`, na.rm=TRUE), `Relative Humidity` = mean(`Relative Humidity`, na.rm=TRUE)) %>% 
    ggplot(aes(x=`Relative Humidity`, y=GHI)) + geom_point() + labs(title="Average GHI by Month vs. Humidity")
  
  vsAlbedo <- city_data[[i]] %>% 
    group_by(Year, Month) %>% 
    summarise(`GHI` = mean(`GHI`, na.rm=TRUE), `Surface Albedo` = mean(`Surface Albedo`, na.rm=TRUE)) %>% 
    ggplot(aes(x=`Surface Albedo`, y=GHI)) + geom_point() + labs(title="Average GHI by Month vs. Surface Albedo")
  
  vsWindS <- city_data[[i]] %>% 
    group_by(Year, Month) %>% 
    summarise(`GHI` = mean(`GHI`, na.rm=TRUE), `Wind Speed` = mean(`Wind Speed`, na.rm=TRUE)) %>% 
    ggplot(aes(x=`Wind Speed`, y=GHI)) + geom_point() + labs(title="Average GHI by Month vs. Wind Speed")
  
  vsPressure <- city_data[[i]] %>% 
    group_by(Year, Month) %>% 
    summarise(`GHI` = mean(`GHI`, na.rm=TRUE), `Pressure` = mean(`Pressure`, na.rm=TRUE)) %>% 
    ggplot(aes(x=`Pressure`, y=GHI)) + geom_point() + labs(title="Average GHI by Month vs. Pressure")
  
  vsWindD <- city_data[[i]] %>% 
    group_by(Year, Month) %>% 
    summarise(`GHI` = mean(`GHI`, na.rm=TRUE), `Wind Direction` = mean(`Wind Direction`, na.rm=TRUE)) %>% 
    ggplot(aes(x=`Wind Direction`, y=GHI)) + geom_point() + labs(title="Average GHI by Month vs. Wind Direction")
  
  vsPrecip <- city_data[[i]] %>% 
    group_by(Year, Month) %>% 
    summarise(`GHI` = mean(`GHI`, na.rm=TRUE), `Precipitable Water` = mean(`Precipitable Water`, na.rm=TRUE)) %>% 
    ggplot(aes(x=`Precipitable Water`, y=GHI)) + geom_point() + labs(title="Average GHI by Month vs. Precipitable Water")
  
  vsZenith <- city_data[[i]] %>%
    group_by(`Solar Zenith Angle`) %>%
    summarise(average_ghi = mean(GHI, na.rm=TRUE)) %>%
    ggplot(aes(x=`Solar Zenith Angle`, y=average_ghi)) + geom_point() + labs(title="Average GHI by Month vs. Precipitable Water")
  
  vsCloud <- city_data[[i]] %>%
    group_by(`Cloud Type`) %>%
    summarise(average_ghi = mean(GHI, na.rm=TRUE)) %>%
    ggplot(aes(x=`Cloud Type`, y=average_ghi)) + geom_point() + labs(title="Average GHI by Month vs. Cloud Type")
  
  plots <- list(temp, dew, humidity, albedo, wind, pressure, windD, precip, zenith, ghi, cloud)
  append(allPlots[[i]], plots)
  plotsVs <- list(vsTemp, vsDew, vsHumid, vsAlbedo, vsWindS, vsPressure, vsWindD, vsPrecip, vsZenith, vsCloud)
  append(allPlots[[i]], plotsVs)
  
# ----------------------------------------------------------------------------------------------------------------------------------
  
  city_data[[i]]$Zenith_Bins <- cut(city_data[[i]]$`Solar Zenith Angle`, breaks = seq(0, 180, by = 10))
  
  # Plotting irradiance vs zenith angle
  # The gray dots are outliers of solar irradiance, likely caused by clouds
  p1 <- ggplot(data = city_data[[i]], aes(x = Zenith_Bins, y = GHI)) +
    geom_boxplot(outlier.color = "gray", size = 0.5) +
    labs(x = "Solar Zenith Angle (degrees)", y = "Global Horizontal Irradiance (W/m²)",
         title = "Distribution of GHI for Different Solar Zenith Angle (Grouped by bins of 10 degrees)") +
    theme_minimal() +
    theme(axis.text.x = element_text(angle = 45, hjust = 1))
  
  # plotting solar zenith against time of day
  p2 <- ggplot(data = city_data[[i]], aes(x = Hour, y = `Solar Zenith Angle`, group = interaction(Month, Day), color = factor(Month))) +
    geom_line() +
    labs(x = "Time of Day (Hour)", y = "Solar Zenith Angle (degrees)",
         title = "Solar Zenith Angle by Time of Day (Spaghetti Plot)") +
    scale_color_discrete(name = "Month", labels = c("January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December")) +
    theme_minimal() +
    theme(legend.position = "top", axis.text.x = element_text(angle = 45, hjust = 1))
  
  
  # shows the difference between solstices, and their effect on solar zenith angle
  filtered_data <- city_data[[i]] %>%
    filter(Month %in% c(6, 12))
  
  p3 <- ggplot(data = filtered_data, aes(x = Hour, y = `Solar Zenith Angle`, group = interaction(Month, Day), color = factor(Month))) +
    geom_line() +
    labs(x = "Time of Day (Hour)", y = "Solar Zenith Angle (degrees)",
         title = "Solar Zenith Angle by Time of Day (June and December Only)") +
    scale_color_discrete(name = "Month", labels = c("June", "December")) +
    theme_minimal() +
    theme(legend.position = "top", axis.text.x = element_text(angle = 45, hjust = 1))
  
  
  #plotting how solar irradiance is affected by time of month
  city_data[[i]]$Month <- factor(city_data[[i]]$Month, levels = 1:12, labels = c("Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"))
  agg_data <- city_data[[i]] %>%
    group_by(Month, Hour) %>%
    summarize(Avg_GHI = mean(GHI))
  p4 <- ggplot(data = city_data[[i]], aes(x = Hour, y = GHI, group = interaction(Month, Hour), color = Month)) +
    geom_line(size = 1.5, alpha = 0.7) +  # Set the size to 1.5 (adjust as needed)
    labs(x = "Hour of the Day", y = "Average Global Horizontal Irradiance (W/m²)",
         title = "Average Solar Irradiance by Hour for Each Month (Spaghetti Plot)") +
    scale_x_continuous(breaks = seq(0, 23, by = 1)) +
    theme_minimal() +
    theme(legend.position = "top", axis.text.x = element_text(angle = 45, hjust = 1))
  
  
  city_data[[i]] <- city_data[[i]] %>%
    rename(Cloud_Type = `Cloud Type`)
  city_data[[i]]$Cloud_Type <- as.factor(city_data[[i]]$Cloud_Type)
  
# -----------------------------------------------------------------------------------------------------
  
  # Effect of clouds on GHI
  p5 <- ggplot(data = city_data[[i]], aes(x = Cloud_Type, y = GHI)) +
    stat_summary(data = subset(city_data[[i]], `Solar Zenith Angle` >= 0 & `Solar Zenith Angle` <= 80),
                 fun = "mean", geom = "bar", fill = "skyblue", color = "black") +
    labs(x = "Cloud_Type", y = "Mean Global Horizontal Irradiance (W/m²)",
         title = "Effect of Cloud Type on Irradiance (Solar Zenith: 0-80 degrees)") +
    theme_minimal() +
    theme(axis.text.x = element_text(angle = 45, hjust = 1))
  
  names(city_data[[i]])
  
  # temperature vs irradiance boxplot
  p6 <- ggplot(data = subset(city_data[[i]], `Solar Zenith Angle` >= 0 & `Solar Zenith Angle` <= 80),
         aes(x = cut(Temperature, breaks = seq(min(Temperature), max(Temperature) + 2, by = 2)), y = GHI)) +
    geom_boxplot() +
    labs(x = "Temperature (°C)", y = "Global Horizontal Irradiance (W/m²)",
         title = "Temperature vs. Global Horizontal Irradiance (Solar Zenith: 0-80 degrees)") +
    theme_minimal()
  
  
  #Surface Albedo vs Irradiance for sunlight hours
  filtered_data <- city_data[[i]] %>%
    filter(`Solar Zenith Angle` >= 0 & `Solar Zenith Angle` <= 80,
           `Surface Albedo` >= 0.10 & `Surface Albedo` <= 0.25)
  filtered_data <- filtered_data %>%
    mutate(Albedo_Bin = cut(`Surface Albedo`, breaks = seq(0.10, 0.25, by = 0.005)),)
  p7 <- ggplot(data = filtered_data, aes(x = Albedo_Bin, y = GHI)) +
    geom_boxplot(outlier.color = "gray", size = 0.5) +
    labs(x = "Surface Albedo", y = "Global Horizontal Irradiance (W/m²)",
         title = "Distribution of GHI for Different Surface Albedo (Grouped by bins of 0.005)\n(Zenith: 0-80 degrees)") +
    theme_minimal() +
    theme(axis.text.x = element_text(angle = 45, hjust = 1))
  
  #Relative humidity vs Solar Irradiance for zentih 0-80
  filtered_data <- filtered_data %>%
    mutate(RelHumidity_Bin = cut(`Relative Humidity`, breaks = seq(0, 100, by = 2.5)))
  p8 <- ggplot(data = filtered_data, aes(x = RelHumidity_Bin, y = GHI)) +
    geom_boxplot(fill = "skyblue", color = "black") +
    labs(x = "Relative Humidity (%)", y = "Global Horizontal Irradiance (W/m²)",
         title = "GHI vs. Relative Humidity (Zenith: 0-80 degrees, Bin Size: 2.5%)") +
    theme_minimal() +
    theme(axis.text.x = element_text(angle = 45, hjust = 1))
  
  #Precipitable Water vs GHI (for hours during sunlight)
  filtered_data <- filtered_data %>%
    mutate(PrecipitableWater_Bin = cut(`Precipitable Water`, breaks = seq(min(`Precipitable Water`), max(`Precipitable Water`), by = 0.15)))
  p9 <- ggplot(data = filtered_data, aes(x = PrecipitableWater_Bin, y = GHI)) +
    geom_boxplot(fill = "skyblue", color = "black") +
    labs(x = "Precipitable Water (Bin Size: 0.05)", y = "Global Horizontal Irradiance (W/m²)",
         title = "GHI vs. Precipitable Water (Zenith: 0-80 degrees)") +
    theme_minimal() +
    theme(axis.text.x = element_text(angle = 45, hjust = 1))

  p <- list(p1, p2, p3, p4, p5, p6, p7, p8, p9)
  append(allPlots[[i]], p)
}
```

```{r}
allPlots[[1]]
allPlots[[2]]
allPlots[[3]]
```
