---
title: "Txs_wind_EDA.Rmd"
date: "2023-07-28"
output:
  html_document:
    code_folding: hide
    highlight: haddock
    theme: lumen
    toc: yes
    toc_depth: 4
    toc_float: yes
    number_sections: yes
  pdf_document:
    toc_depth: '4'
    number_sections: yes
urlcolor: blue
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(scipen = 0, digits = 3)  # controls base R output
# check if you have ISLR package, if not, install it
if(!require('pacman')) {install.packages('pacman')}
pacman::p_load(ISLR, readxl, tidyverse, magrittr, dplyr, ggplot2, ggrepel, data.table, lubridate, ggpubr, patchwork)
```



```{r}
og_df <- read.csv("data/TexasTurbine.csv")
teor_df <- read.csv("data/form_output_txs.csv")
names(og_df)
names(teor_df)
og_df <- og_df %>%
  rename(
    time_stamp = Time.stamp,
    power_generated = System.power.generated....kW.,
    wind_speed = Wind.speed....m.s.,
    wind_direction = Wind.direction....deg.,
    pressure = Pressure....atm.,
    air_temperature = Air.temperature.....C.
  )

teor_df <- teor_df %>%
  rename(
    power_curve_turbine_output = Power.curve.turbine.output.array....kW.,
    power_curve_wind_speed = Power.curve.wind.speed.array....m.s.
  )

Cp <- 0.35  # Efficiency factor (in decimal)
r <- 1.225  # Air density at standard conditions (in kg/m^3)
R <- 111/2    # Blade length of the wind turbine (in meters)
sc <- 0.0001  # Scaling variable






```
