---
title: "Map.Rmd"
output: html_document
date: "2023-08-02"
---

```{r}
if(!require('pacman')) {install.packages('pacman')}
pacman::p_load(dplyr, ggplot2, ggrepel, data.table, lubridate, ggpubr, patchwork, car, glmnet, sf, purrr, caret, xgboost)
```

```{r}
remove_first_two <- function(x) {
  x[-(1:2)]
}

get_first_two <- function(x) {
  x[(1:2)]
}

files <- list.files(path="data/MapData/raw", pattern="\\.csv$", full.names=TRUE)
files_no_path <- list.files(path="data/MapData/raw", pattern="\\.csv$", full.names=FALSE)
read <- lapply(files, readLines)
first_two <- lapply(read, get_first_two)
read <- lapply(read, remove_first_two)

for(i in 1:length(files)) {
  fwrite(read[i], file=(paste0("data/MapData/cleaned/", "data", files_no_path[i])), quote=FALSE)
  fwrite(first_two[i], file=(paste0("data/MapData/cleaned/", "info", files_no_path[i])), quote=FALSE)
}


files_cleaned <- list.files(path="data/MapData/cleaned", pattern="data.*\\.csv$", full.names=TRUE)
f_cleaned <- lapply(files_cleaned, fread)

info_cleaned <- list.files(path="data/MapData/cleaned", pattern="info.*\\.csv$", full.names=TRUE)
i_cleaned <- lapply(info_cleaned, fread)
for(i in 1:length(f_cleaned)) {
  f_cleaned[[i]]$ID <- i_cleaned[[i]]$`Location ID`  
  f_cleaned[[i]]$Long <- i_cleaned[[i]]$Longitude
  f_cleaned[[i]]$Lat <- i_cleaned[[i]]$Latitude
}

full <- f_cleaned %>% reduce(full_join)
full <- full[which(full$`Solar Zenith Angle` < 90)]
data.processed <- full
data.processed$`Cloud Type` <- as.factor(data.processed$`Cloud Type`)
# one hot encoding on the cloud type using caret 
dummy <- dummyVars(" ~.", data=data.processed)
data.processed <- data.frame(predict(dummy, data.processed))

# cyclical encoding on wind direction, month, day, hour, minute
data.processed <- data.processed %>% mutate(sinWD= sin(X.Wind.Direction. * pi / 180), cosWD = cos(X.Wind.Direction. * pi / 180)) %>% select(-X.Wind.Direction.)
data.processed <- data.processed %>% mutate(sin.month = sin(2 * pi * Month / 12), cos.month = cos(2 * pi * Month / 12), sin.day = sin(2 * pi * Day / 31), cos.day = cos(2 * pi * Day / 31), sin.hour = sin(2 * pi * Hour / 24), cos.hour = cos(2 * pi * Hour / 24), sin.minute = sin(2 * pi * Minute / 60), cos.minute = cos(2 * pi * Minute / 60)) %>% select(-c(Month, Day, Hour, Minute))

# min max standardization on X variables (do not change y variable)
ghi_col <- data.processed$GHI
data.processed <- data.processed %>% select(-c(GHI, Year, ID, Long, Lat))
processed <- preProcess(data.processed, method=c("range"))
data.processed <- predict(processed, data.processed)
data.processed$GHI <- ghi_col
data.processed$X.Cloud.Type.2 <- 0
data.processed$X.Cloud.Type.10 <- 0
data.processed$Year <- (21/20)


data.processed <- data.processed[, c(32, 1, 15, 18, 13, 2, 14, 17, 16, 3, 4, 30, 5, 6, 8, 9, 10, 11, 31, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29)]

# data.processed <- data.processed[,c(1, 12, 17, 18, 13, 2, 16, 15, 14, 3, 30, 4, 5, 6, 8, 9, 10, 11, 31, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29)]
data_x <- data.matrix(data.processed[,-ncol(data.processed)])
data_y <- data.matrix(data.processed[,ncol(data.processed)])


fitXGB <- xgb.load("XGB300K")
predictions <- predict(fitXGB, data_x)
RMSE(data_y, predictions)
R2(data_y, predictions)

full$PredGHI <- predictions

full <- fread("data/mapJoined.csv")

avg_long = mean(full$Long)
avg_lat = mean(full$Lat)

sums <- full %>% group_by(ID) %>% mutate(sumGHI = sum(PredGHI)) %>% select(ID, Long, Lat, sumGHI) %>% unique()
# sums[nrow(sums) + 1,] = list(0, avg_long, avg_lat, mean(sums$sumGHI))
sums <- sums[1:192,]

stFull <- st_as_sf(sums, coords=c("Long", "Lat"), crs=4326)

avg.df = data.frame(Long=numeric(), Lat=numeric())
avg.df[1,] = c(avg_long, avg_lat)
center <- st_as_sf(avg.df, coords=c("Long", "Lat"), crs=4326)

stFull <- stFull %>% mutate(dist = as.numeric(st_distance(center, geometry)[1]))

class(stFull[1, 3])
class(center)

center <- st_geometry(center)

# stFullTemp <- stFull %>% mutate(cost = sumGHI * (0.9999)^(dist / 1000))

# stFull[nrow(stFull) + 1,] = list(0, mean(stFull$sumGHI), center, 0)
stFull <- stFull %>% mutate(Power = sumGHI * (0.9999)^(dist / 1000))
# stFullTemp %>% ggplot() + geom_sf(aes(color=cost)) + scale_color_gradient(low="blue", high="red") 
heatMap <- stFull %>% ggplot() + geom_sf(aes(color=Power, size = Power)) + scale_color_gradient(low="blue", high="red") 
ggsave("heatmap_final.png", heatMap)
```