---
title: "LVEDA.Rmd"
output: html_document
date: "2023-07-28"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(scipen = 0, digits = 3)  # controls base R output
# check if you have ISLR package, if not, install it
if(!require('pacman')) {install.packages('pacman')}
pacman::p_load(ISLR, readxl, tidyverse, magrittr, dplyr, ggplot2, ggrepel, data.table, lubridate)
```


```{r}
# coordinates are 36.17, -115.14

remove_first_two <- function(x) {
  x[-(1:2)]
}

lv_files <- list.files(path="data/Las_Vegas_Solar_Irradiation/raw", pattern="\\.csv$", full.names=TRUE)
lv_files_no_path <- list.files(path="data/Las_Vegas_Solar_Irradiation/raw", pattern="\\.csv$", full.names=FALSE)
lv_read <- lapply(lv_files, readLines)
lv_read <- lapply(lv_read, remove_first_two)

for(i in 1:length(lv_files)) {
  fwrite(lv_read[i], file=(paste0("data/Las_Vegas_Solar_Irradiation/cleaned/",lv_files_no_path[i])), quote=FALSE)
}


lv_files_cleaned <- list.files(path="data/Las_Vegas_Solar_Irradiation/cleaned", pattern="\\.csv$", full.names=TRUE)
lv_cleaned <- lapply(lv_files_cleaned, fread)

lv_full <- lv_cleaned %>% reduce(full_join)

fwrite(lv_full, file="data/Las_Vegas_Solar_Irradiation/LV.csv")


ny_files <- list.files(path="data/NY_Solar_Irradiation/raw", pattern="\\.csv$", full.names=TRUE)
ny_files_no_path <- list.files(path="data/NY_Solar_Irradiation/raw", pattern="\\.csv$", full.names=FALSE)
ny_read <- lapply(ny_files, readLines)
ny_read <- lapply(ny_read, remove_first_two)

for(i in 1:length(ny_files)) {
  fwrite(ny_read[i], file=(paste0("data/NY_Solar_Irradiation/cleaned/",ny_files_no_path[i])), quote=FALSE)
}


ny_files_cleaned <- list.files(path="data/NY_Solar_Irradiation/cleaned", pattern="\\.csv$", full.names=TRUE)
ny_cleaned <- lapply(ny_files_cleaned, fread)

ny_full <- ny_cleaned %>% reduce(full_join)

fwrite(ny_full, file="data/NY_Solar_Irradiation/ny.csv")

chicago_files <- list.files(path="data/Chicago_Solar_Irradiation/raw", pattern="\\.csv$", full.names=TRUE)
chicago_files_no_path <- list.files(path="data/Chicago_Solar_Irradiation/raw", pattern="\\.csv$", full.names=FALSE)
chicago_read <- lapply(chicago_files, readLines)
chicago_read <- lapply(chicago_read, remove_first_two)

for(i in 1:length(chicago_files)) {
  fwrite(chicago_read[i], file=(paste0("data/Chicago_Solar_Irradiation/cleaned/",chicago_files_no_path[i])), quote=FALSE)
}


chicago_files_cleaned <- list.files(path="data/Chicago_Solar_Irradiation/cleaned", pattern="\\.csv$", full.names=TRUE)
chicago_cleaned <- lapply(chicago_files_cleaned, fread)

chicago_full <- chicago_cleaned %>% reduce(full_join)

fwrite(chicago_full, file="data/Chicago_Solar_Irradiation/chicago.csv")

chicago_full <- chicago_full$Location = 'Chicago'
ny_full <- ny_full$Location = 'New York'
lv_full <- lv_full$Location = 'Las Vegas'

data = list(lv_full, ny_full, chicago_full)
all_data <- data %>% reduce(full_join)
fwrite(all_data, file="data/SolarFull.csv")
```