---
title: "SolarModeling2.Rmd"
output: html_document
date: "2023-07-30"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(scipen = 0, digits = 3)  # controls base R output
# check if you have ISLR package, if not, install it
if(!require('pacman')) {install.packages('pacman')}
pacman::p_load(ISLR, readxl, tidyverse, magrittr, dplyr, ggplot2, ggrepel, data.table, lubridate, ggpubr, patchwork, car, glmnet, e1071, caret)
```

```{r}
solarData <- fread("data/SolarFull.csv")
solarData$`Cloud Type` <- as.factor(solarData$`Cloud Type`)
```

```{r}

solarData <- (solarData[which(solarData$`Solar Zenith Angle` < 90)])

summary(solarData)

N <- length(solarData$GHI) 
n1 <- floor(.8*N)
set.seed(10)
# Split data to three portions of .6, .2 and .2 of data size N
idx_train <- sample(N, n1)
idx_no_train <- (which(! seq(1:N) %in% idx_train))
data.train <- solarData[idx_train,]
data.test <- solarData[idx_no_train,]

names(solarData)


fit <- lm(GHI ~ ., data.train)
summary(fit)

fitNoLoc <- lm(GHI ~ .-Location, data.train)
summary(fitNoLoc)

fitTemp <- lm(GHI ~ Temperature, data.train)

# data.test$Prediction.noLoc <- predict(fitNoLoc, data.test, type="response")
# data.test <- data.test %>% mutate(sq.resid.noLoc = (Prediction.noLoc - GHI) * (Prediction.noLoc - GHI))
# MSE.noLoc <- mean(data.test$sq.resid.noLoc)
# MSE.noLoc
# 
# 
# data.test$Prediction.withLoc <- predict(fit, data.test, type="response")
# data.test <- data.test %>% mutate(sq.resid.loc = (Prediction.withLoc - GHI) * (Prediction.withLoc - GHI))
# MSE.Loc <- mean(data.test$sq.resid.loc)
# MSE.Loc


# with backwards elimination
Anova(fitNoLoc)
summary(fitNoLoc)
# fitNoLoc <- update(fitNoLoc, .~.-`Wind Direction`)
# fitNoLoc <- update(fitNoLoc, .~.-`Temperature`)
# fitNoLoc <- update(fitNoLoc, .~.-`Hour`)
fitNoLoc.backwards <- update(fitNoLoc, .~.-`Day`)
fitNoLoc.backwards <- update(fitNoLoc, .~.-`Wind Speed`)
fitNoLoc.backwards <- update(fitNoLoc, .~.-`Minute`)

# fitNoLoc <- update(fitNoLoc, .~.-`Dew Point`)
Anova(fitNoLoc.backwards)
summary(fitNoLoc.backwards)

getStats <- function(fit, testing_data) {
  testing_data$predict <- predict(fit, testing_data, type="response")
  real.mean <- mean(testing_data$GHI)
  testing_data <- testing_data %>% mutate(sq.resid = (predict - GHI) * (predict - GHI), abs.resid <- abs(predict - GHI), diff.mean <- abs(GHI - real.mean))
  RMSE <- sqrt(mean(testing_data$sq.resid))
  MAE <- mean(testing_data$abs.resid)
  RAE <- sum(testing_data$abs.resid) / sum(testing_data$diff.mean)
  
  return(list(RMSE, MAE, RAE))
}

getStats(fit, data.test)
getStats(fitNoLoc, data.test)
getStats(fitNoLoc.backwards, data.test)

# plot(fitNoLoc)

```

```{r, normalize/preprocess all data}
# no standardization as the data is likely not in a bell curve, can try to do a gaussian standardization later
# first we remove location
data.processed <- solarData %>% select(-Location)
# then we do a one hot encoding on the cloud type
dummy <- dummyVars(" ~.", data=data.processed)
data.processed <- data.frame(predict(dummy, data.processed))

# cyclical encoding on month, day, hour, minute, and wind direction
data.processed <- data.processed %>% mutate(sinWD= sin(X.Wind.Direction. * pi / 180), cosWD = cos(X.Wind.Direction. * pi / 180)) %>% select(-X.Wind.Direction.)

data.processed <- data.processed %>% mutate(sin.month = sin(2 * pi * Month / 12), cos.month = cos(2 * pi * Month / 12), sin.day = sin(2 * pi * Day / 31), cos.day = cos(2 * pi * Day / 31), sin.hour = sin(2 * pi * Hour / 24), cos.hour = cos(2 * pi * Hour / 24), sin.minute = sin(2 * pi * Minute / 60), cos.minute = cos(2 * pi * Minute / 60)) %>% select(-c(Month, Day, Hour, Minute))

# min max standardization
processed <- preProcess(data.processed, method=c("range"))
data.processed <- predict(processed, data.processed)
```

```{r}

N <- length(data.processed$GHI) 
n1 <- floor(.8*N)
set.seed(10)
# Split data to three portions of .6, .2 and .2 of data size N
idx_train <- sample(N, n1)
idx_no_train <- (which(! seq(1:N) %in% idx_train))
data.train <- data.processed[idx_train,]
data.test <- data.processed[idx_no_train,]

# run SVR
fitSVR <- svm(GHI ~ ., data.train)
```

```{r, trying LASSO instead}
#Step 1: Prepare design matrix
Y <- solarData$GHI # extract Y
X.fl <- model.matrix(GHI~., data=solarData)[, -1] # take the first column's of 1 out #Step 2: Find x's output from LASSO with min cross-validation error
set.seed(10) # to control the ramdomness in K folds
fit.fl.cv <- cv.glmnet(X.fl, Y, alpha=1, nfolds=10, intercept = T)

plot(fit.fl.cv)

coef.min <- coef(fit.fl.cv, s="lambda.1se") #s=c("lambda.1se","lambda.min") or lambda value
coef.min.nonzero <- coef.min[which(coef.min !=0),] # get the non=zero coefficients
var.min <- rownames(as.matrix(coef.min))[-1] # output the names dim(as.matrix(coef.min))
```