---
title: "SolarModeling"
output: html_document
date: "2023-07-30"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(scipen = 0, digits = 3)  # controls base R output
# check if you have ISLR package, if not, install it
if(!require('pacman')) {install.packages('pacman')}
pacman::p_load(ISLR, readxl, tidyverse, magrittr, dplyr, ggplot2, ggrepel, data.table, lubridate, ggpubr, patchwork, car, glmnet, keras, caret)
```


```{r}
solarData_ML <- fread("data/SolarFull.csv")
solarData_ML$`Cloud Type` <- as.factor(solarData_ML$`Cloud Type`)
solarData_ML <- solarData_ML[solarData_ML$`Solar Zenith Angle` < 90]
vars_to_drop <- c("Year", "Month", "Day", "Hour", "Minute", "Location", "Cloud Type")
solarData_ML_filtered <- solarData_ML %>% select(-one_of(vars_to_drop))
solarData_ML_filtered <- na.omit(solarData_ML_filtered)

set.seed(69)
index <- createDataPartition(solarData_ML_filtered$GHI, p = 0.8, list = FALSE)
train_data <- solarData_ML_filtered[index, ]
test_data <- solarData_ML_filtered[-index, ]

x_train <- as.matrix(select(train_data, -GHI))
y_train <- as.vector(train_data$GHI)
x_test <- as.matrix(select(test_data, -GHI))
y_test <- as.vector(test_data$GHI)

model <- keras_model_sequential() %>%
  layer_dense(units = 64, activation = "sigmoid", input_shape = ncol(x_train)) %>%
  layer_dense(units = 64, activation = "relu") %>%
  layer_dense(units = 16, activation = "relu") %>%
  layer_dense(units = 1)

model %>% compile(
  loss = "mean_squared_error",
  optimizer = optimizer_adam(),
  metrics = c("mean_squared_error")
)

history <- model %>% fit(
  x_train, y_train,
  epochs = 13,
  batch_size = 32,
  validation_split = 0.2
)

model_path <- "ML_models/solar_irr_general_not_scaled.h5"
save_model_hdf5(model, model_path)

metrics <- model %>% evaluate(x_test, y_test)
metrics

```



```{r}
loaded_model <- load_model_hdf5(model_path)
y_pred <- loaded_model %>% predict(x_test)
comparison_df <- data.frame(Actual = y_test, Predicted = y_pred)
# metrics <- loaded_model %>% evaluate(x_test, y_test)
# metrics
write.csv(comparison_df, "data/comparison_results.csv", row.names = FALSE)
```